#!/bin/bash
#PBS -k o
#PBS -l nodes=1:ppn=8,walltime=00:30:00

## modules
echo "Loading modules"
module unload matlab
module load matlab/2017a
module load spm/8
module unload python
module load dipy/dev
echo "Finished loading modules"

export PYTHONPATH=/N/u/brlife/git/nibabel:$PYTHONPATH

echo "copying moving and static tractograms"
subjID=`jq -r '._inputs[0].meta.subject' config.json`
static=`jq -r '.tractogram_static' config.json`
t1_static=`jq -r '.t1_static' config.json`
segmentations=`jq -r '.segmentations' config.json`
movings=`jq -r '.tractograms_moving' config.json`
t1s=`jq -r '.t1s_moving' config.json`

# Building arrays
arr_seg=()
arr_seg+=(${segmentations})
arr_mov=()
arr_mov+=(${movings})
arr_t1s=()
arr_t1s+=(${t1s})

echo "Check the inputs subject id"
num_ex=$((${#arr_seg[@]} - 2))

echo "Build a wmc structure"
run=`jq -r '.run' config.json`
stat_sub=\'$subjID\'
mov_sub=\'$run\'
matlab -nosplash -nodisplay -r "build_wmc_structure($stat_sub, $mov_sub)";
#singularity exec docker://brainlife/mcr:neurodebian1604-r2017a ./compiled/build_wmc_structure $subjID $mov_afq_id
if [ -f 'output.mat' ]; then 
    echo "WMC structure created."
else 
	echo "WMC structure missing."
	exit 1
fi

echo "Complete"
